// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Manifold = { id: string, curvature: number, points: Array<string>, entropy: number, };

export type QuantumPoint = { id: string, coordinates: Array<number>, metadata: string, q_value: number, visits: bigint, success_count: bigint, success_rate: number, resonance: number, entropy: number, };

export type VshState = { total_points: number, entropy: number, };

export type GlobalState = {
  total_points: number;
  entropy: number;
  cpu_usage: number;
  ram_percentage: number;
  status: string;
  liquid_equity: number;
  total_nodes: number;
};