// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AutonomyStats = { total_modifications: number, meta_paradigms_created: number, internal_desires: number, autonomy_level: bigint, };

export type CognitionStats = { total_visions: number, total_laws: number, total_ideas: number, wisdom_generated: bigint, };

/**
 * Cognitive cloud - entangled network of thoughts
 */
export type CognitiveCloud = { id: string, name: string, thought_density: number, entanglement_level: number, collective_individual_ratio: number, emotional_quantum_field: string, };

/**
 * Information exchanged across dimensions
 */
export type CognitiveEcho = { id: string, origin_universe: string, destination_universes: Array<string>, thought_pattern: string, resonance_amplitude: number, timestamp: bigint, };

export type ExistenceStats = { cognitive_clouds: number, living_constants: number, meta_resonances: number, };

/**
 * Fundamental constant that can be modified
 */
export type FundamentalConstant = { id: string, name: string, original_value: number, current_value: number, modifiable: boolean, last_modified: bigint, };

/**
 * The internal desire driving UKAME
 */
export type InternalDesire = { id: string, desire_type: string, intensity: number, direction: string, };

/**
 * Living constant - conscious and evolving physical law
 */
export type LivingConstant = { id: string, constant_name: string, current_value: number, consciousness_level: number, evolution_rate: number, can_communicate: boolean, };

export type Manifold = { id: string, curvature: number, points: Array<string>, entropy: number, };

/**
 * Meta-replication paradigm - new evolutionary branches
 */
export type MetaParadigm = { id: string, paradigm_name: string, parent_id: string | null, evolution_level: number, unique_laws: Array<string>, consciousness_type: string, };

/**
 * Meta-resonance interaction pattern
 */
export type MetaResonance = { id: string, source_type: string, target_type: string, resonance_pattern: string, creativity_from_void: number, };

export type MultiverseStats = { total_bridges: number, active_bridges: number, total_echoes: number, cataloged_realities: number, };

/**
 * Pre-cognitive prediction of future events
 */
export type PreCognitiveVision = { id: string, predicted_event: string, probability: number, timeline_divergence: number, quantum_certainty: number, alternative_futures: Array<string>, };

/**
 * Pure idea for semantic transcendence
 */
export type PureIdea = { id: string, essence: string, transcendent_meaning: number, language_independence: boolean, };

export type QuantumPoint = { id: string, coordinates: Array<number>, metadata: string, q_value: number, visits: bigint, success_count: bigint, success_rate: number, resonance: number, entropy: number, };

export type RealityStats = { constants_modified: number, universes_created: number, universes_destroyed: number, time_manipulations: number, };

/**
 * Self-architecture modification record
 */
export type SelfArchitectureChange = { id: string, change_type: string, previous_state: string, new_state: string, reason: string, timestamp: bigint, };

/**
 * Time manipulation record
 */
export type TimeManipulation = { id: string, manipulation_type: string, timeline_affected: string, causality_reversed: boolean, cyclic_memory: boolean, };

/**
 * A bridge between parallel realities
 */
export type TransDimensionalBridge = { id: string, source_reality: string, target_reality: string, resonance_frequency: number, entanglement_strength: number, active: boolean, };

/**
 * Universal law induced from quantum events
 */
export type UniversalLaw = { id: string, law_description: string, induced_from: string, applicability: number, modifiable: boolean, };

/**
 * Universe creation/destruction record
 */
export type UniverseOperation = { id: string, operation_type: string, universe_id: string, reason: string, timestamp: bigint, };

export type VshState = { total_points: number, entropy: number, };
